"""
XL Fitness AI — Weight Plate YOLO Training Script
Fine-tunes YOLOv11 to detect AlphaFit barbell plate stripes.

Dataset format (YOLO):
    data/weight_plates/
        images/
            train/   *.jpg
            val/     *.jpg
        labels/
            train/   *.txt   (YOLO: class x_c y_c w h, all normalised)
            val/     *.txt
        dataset.yaml         (auto-generated by this script)

Classes:
    0  red_plate     25 kg
    1  blue_plate    20 kg
    2  yellow_plate  15 kg
    3  green_plate   10 kg
    4  white_plate    5 kg

Camera setup:
    • Mounted on barbell frame looking along the sleeve from the side (~45°)
    • Two cameras per station (one each side) — at least one always has a clear view
    • Label the visible stripe ring on each plate — each plate = one bounding box

Usage:
    python3 weight_id/train.py
    python3 weight_id/train.py --data data/weight_plates --epochs 150 --model yolo11s.pt
"""

import argparse
import os
import sys
import shutil
import yaml
from pathlib import Path


CLASS_NAMES = [
    "red_plate",     # 25 kg — red stripe
    "blue_plate",    # 20 kg — blue stripe
    "yellow_plate",  # 15 kg — yellow stripe
    "green_plate",   # 10 kg — green stripe
    "white_plate",   # 5 kg  — white stripe (grey/cream in some lights)
]

KG_PER_CLASS = {i: [25, 20, 15, 10, 5][i] for i in range(5)}


def build_dataset_yaml(data_dir: Path) -> Path:
    yaml_path = data_dir / "dataset.yaml"
    cfg = {
        "path":  str(data_dir.resolve()),
        "train": "images/train",
        "val":   "images/val",
        "nc":    len(CLASS_NAMES),
        "names": CLASS_NAMES,
    }
    with open(yaml_path, "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"[weight_train] dataset.yaml → {yaml_path}")
    return yaml_path


def check_dataset(data_dir: Path) -> tuple:
    dirs = [
        data_dir / "images" / "train",
        data_dir / "images" / "val",
        data_dir / "labels" / "train",
        data_dir / "labels" / "val",
    ]
    missing = [str(d) for d in dirs if not d.exists()]
    if missing:
        print("ERROR: Missing dataset directories:")
        for m in missing:
            print(f"  {m}")
        print()
        print("Expected structure:")
        print("  data/weight_plates/")
        print("    images/train/*.jpg")
        print("    images/val/*.jpg")
        print("    labels/train/*.txt  (YOLO format)")
        print("    labels/val/*.txt")
        print()
        print("Use pose/label.html or CVAT to annotate plate stripes.")
        sys.exit(1)

    n_train = len(list((data_dir / "images" / "train").glob("*.jpg")))
    n_val   = len(list((data_dir / "images" / "val").glob("*.jpg")))
    print(f"[weight_train] Dataset: {n_train} train images, {n_val} val images")

    if n_train < 50:
        print(f"  WARNING: Only {n_train} training images. Aim for 50+ per class ({50 * len(CLASS_NAMES)}+ total).")
    return n_train, n_val


def train(args):
    try:
        from ultralytics import YOLO
    except ImportError:
        print("ERROR: ultralytics not installed. Run: pip install ultralytics")
        sys.exit(1)

    data_dir = Path(args.data)
    check_dataset(data_dir)
    yaml_path = build_dataset_yaml(data_dir)

    device = _best_device()
    print(f"[weight_train] Starting training")
    print(f"  Base model : {args.model}")
    print(f"  Epochs     : {args.epochs}")
    print(f"  Device     : {device}")
    print(f"  Output     : {args.output}")

    model = YOLO(args.model)
    results = model.train(
        data      = str(yaml_path),
        epochs    = args.epochs,
        imgsz     = args.imgsz,
        batch     = args.batch,
        device    = device,
        patience  = 25,
        name      = "weight_id",
        project   = "runs/weight_id",
        save      = True,
        exist_ok  = True,
    )

    # Export best model to ONNX
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    best_pt = Path(results.save_dir) / "weights" / "best.pt"
    if best_pt.exists():
        best = YOLO(str(best_pt))
        best.export(format="onnx", imgsz=args.imgsz, opset=12)
        onnx_src = best_pt.with_suffix(".onnx")
        if onnx_src.exists():
            shutil.copy(str(onnx_src), str(out))
            print(f"[weight_train] ONNX saved → {out}")
    else:
        print(f"[weight_train] WARNING: best.pt not found at {best_pt}")

    print("[weight_train] Done. Deploy with: make deploy PI=pi@IP")


def _best_device() -> str:
    try:
        import torch
        if torch.backends.mps.is_available():
            return "mps"    # Apple Silicon (Mac Mini M4)
        if torch.cuda.is_available():
            return "0"      # GPU
    except Exception:
        pass
    return "cpu"


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Train YOLOv11 weight plate detector")
    ap.add_argument("--data",   default="data/weight_plates", help="Dataset directory")
    ap.add_argument("--model",  default="yolo11n.pt",         help="Base model (.pt)")
    ap.add_argument("--epochs", type=int, default=100)
    ap.add_argument("--imgsz",  type=int, default=640)
    ap.add_argument("--batch",  type=int, default=16)
    ap.add_argument("--output", default="models/weights/weight_id_v1.onnx")
    train(ap.parse_args())
